### ISSUE TITLE
Theft?

### ISSUE THREAD

**Issue by KjellKod** [tusharsappal/EBooker#1]
Dude are you stealing e-books and putting them up on public github?

**Comment by tusharsappal** [comment]
@KjellKod  , I had these books in my collection from a long time . I have just uploaded them so that everyone can view them . Anyways there are tons of websites which offer books to everyone to download for free . :)

Anyways if this might have hurt you in any way , I can take down this repo or make it private .. :)

**Comment by KjellKod** [comment]
It doesn't hurt me but it hurt these authors. 

Either you are a complete ignorant and clueless willy-nilly SC enthusiast or you are re-publishing them purposefully knowing that this can cause economic damage to said authors but you just don't care.

**Comment by tusharsappal** [comment]
Well , anyways these books are anyways freely available on the internet . I haven't received any complains till date . If some one complains I will remove that book .

**Comment by KjellKod** [comment]
It's up to you of course but since publishing this material without the authors permission is a violation of the copyright laws you should really, for pure decency sake, remove all ebooks you have here. 

I won't bother you any more with this. It's on your conscience and I've given you fair warning

**Comment by tusharsappal** [comment]
I have made this repo as a pvt one . Thanks for reminding me .
